---
# Source: gitlab/charts/postgresql/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-postgresql-metrics
  labels:
    app: postgresql
    chart: postgresql-8.9.4
    release: "RELEASE-NAME"
    heritage: "Helm"
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9187
      targetPort: http-metrics
  selector:
    app: postgresql
    release: RELEASE-NAME
    role: master
