---
# Source: gitlab/charts/gitlab/charts/sidekiq/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: RELEASE-NAME-sidekiq-all-in-1-v1
  namespace: default
  labels:
    app: sidekiq
    chart: sidekiq-4.0.1
    release: RELEASE-NAME
    heritage: Helm
    
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sidekiq
      release: RELEASE-NAME
      queue-pod-name: all-in-1
