---
# Source: gitlab/charts/gitlab-runner/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: RELEASE-NAME-gitlab-runner
  labels:
    app: RELEASE-NAME-gitlab-runner
    chart: gitlab-runner-0.17.0
    release: "RELEASE-NAME"
    heritage: "Helm"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
