---
# Source: gitlab/charts/prometheus/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-10.0.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-server
