---
# Source: gitlab/charts/gitlab/charts/webservice/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-webservice
  namespace: default
  labels:
    app: webservice
    chart: webservice-4.0.1
    release: RELEASE-NAME
    heritage: Helm
    
  annotations:
    kubernetes.io/ingress.class: "RELEASE-NAME-nginx"
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    certmanager.k8s.io/issuer: "RELEASE-NAME-issuer"
spec:
  rules:
    - host: gitlab.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: RELEASE-NAME-webservice
              servicePort: 8181
          - path: /admin/sidekiq
            backend:
              serviceName: RELEASE-NAME-webservice
              servicePort: 8080
  tls:
    - hosts:
      - gitlab.example.com
      secretName: RELEASE-NAME-gitlab-tls
