---
# Source: gitlab/charts/gitlab/charts/webservice/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: RELEASE-NAME-webservice
  namespace: default
  labels:
    app: webservice
    chart: webservice-4.0.1
    release: RELEASE-NAME
    heritage: Helm
    
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: webservice
      release: RELEASE-NAME
