---
# Source: gitlab/charts/gitlab/charts/gitlab-shell/templates/nginx-tcp-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-nginx-ingress-tcp
  namespace: default
  labels:
    app: gitlab-shell
    chart: gitlab-shell-4.0.1
    release: RELEASE-NAME
    heritage: Helm
    
data:
  22: "default/RELEASE-NAME-gitlab-shell:22"
