---
# Source: gitlab/charts/nginx-ingress/templates/controller-stats-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-nginx-ingress-controller-stats
  namespace: default
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.30.0-1
    release: RELEASE-NAME
    heritage: Helm
    
    component: "controller"
spec:
  
  ports:
    - name: stats
      port: 18080
      targetPort: stats
  selector:
    app: nginx-ingress
    component: "controller"
    release: RELEASE-NAME
  type: "ClusterIP"
