---
# Source: gitlab/charts/nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-nginx-ingress-controller
  namespace: default
  labels:
    component: "controller"
    app: nginx-ingress
    chart: nginx-ingress-0.30.0-1
    release: RELEASE-NAME
    heritage: Helm
    
spec:
  
  externalTrafficPolicy: "Local"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: gitlab-shell
      port: 22
      protocol: TCP
      targetPort: gitlab-shell
  selector:
    app: nginx-ingress
    component: "controller"
    release: RELEASE-NAME
  type: "LoadBalancer"
