---
# Source: gitlab/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: RELEASE-NAME-nginx-ingress-default-backend
  namespace: default
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.30.0-1
    release: RELEASE-NAME
    heritage: Helm
    
    component: "default-backend"
spec:
  selector:
    matchLabels:
      app: nginx-ingress
      release: RELEASE-NAME
      component: "default-backend"
  minAvailable: 1
