---
# Source: gitlab/charts/nginx-ingress/templates/headers-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-nginx-ingress-custom-headers
  namespace: default
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.30.0-1
    release: RELEASE-NAME
    heritage: Helm
    
    component: "controller"
data:
  Referrer-Policy: strict-origin-when-cross-origin
