---
# Source: gitlab/charts/certmanager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-cert-manager
  namespace: "default"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance:  RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v0.10.1
