---
# Source: gitlab/charts/redis/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-redis-metrics
  labels:
    app: redis
    chart: redis-10.3.4
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  selector:
    app: redis
    release: RELEASE-NAME
