---
# Source: gitlab/charts/certmanager-issuer/templates/issuer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: RELEASE-NAME-issuer.1
  namespace: default
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: RELEASE-NAME
    heritage: Helm
    
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: certmanager-issuer
        release: RELEASE-NAME
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: RELEASE-NAME-certmanager-issuer
      restartPolicy: OnFailure      
      containers:
        - name: create-issuer
          image: "registry.gitlab.com/gitlab-org/build/cng/kubectl:1.13.12"
          command: ['/bin/bash', '/scripts/create-issuer', '/scripts/issuer.yml']
          
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 50m
      volumes:
      - name: scripts
        configMap:
          name: RELEASE-NAME-certmanager-issuer-certmanager
