---
# Source: gitlab/charts/minio/templates/minio_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-minio
  namespace: default
  labels:
    app: minio
    chart: minio-0.4.3
    release: RELEASE-NAME
    heritage: Helm
    
spec:
  strategy:
    type: Recreate
    # The following entry allows updates without intervention, due to previous defaults.
    rollingUpdate: null
  selector:
    matchLabels:
      app: minio
      release: "RELEASE-NAME"
      component: app
  template:
    metadata:
      name: RELEASE-NAME-minio
      labels:
        app: minio
        chart: "minio-0.4.3"
        release: "RELEASE-NAME"
        heritage: "Helm"
        component: app
      annotations:
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
        - name: export
          persistentVolumeClaim:
            claimName: RELEASE-NAME-minio
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: RELEASE-NAME-minio-config-cm
            - secret:
                name: "RELEASE-NAME-minio-secret"
        - name: minio-server-config
          emptyDir:
            medium: "Memory"
      initContainers:
        - name: configure
          image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          command: ["sh", "/config/configure"]
          volumeMounts:
            - name: minio-configuration
              mountPath: /config
            - name: minio-server-config
              mountPath: /minio
          resources:
            requests:
              cpu: 50m      
      containers:
        - name: minio
          image: minio/minio:RELEASE.2017-12-28T01-21-00Z
          imagePullPolicy: 
          args: ["-C", "/tmp/.minio", "--quiet", "server", "/export"]
          volumeMounts:
            - name: export
              mountPath: /export
            - name: minio-server-config
              # this path altered from upstream, for use with `securityContext`/UID 1000
              mountPath: "/tmp/.minio"
            - name: podinfo
              mountPath: /podinfo
              readOnly: false
          ports:
            - name: service
              containerPort: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
